---
output:
  pdf_document: default
  html_document: default
---
#### Question 1. Coverage Analysis [20 pts]

Download the reads and reference genome from: https://github.com/schatzlab/appliedgenomics2019/raw/master/assignments/assignment2/asm.tgz

Note I have provided both paired-end and mate-pairs reads (see included README for details). 
Make sure to look at all of the reads for the coverage analysis and kmer analysis, as well as in the assembly.

- Question 1a. How long is the reference genome? [Hint: Try `samtools faidx`]

> After trying the following command:  
samtools faidx ref.fa  
we could get a file with .fai extension. The total length of genome is 233806 in bases


\pagebreak

- Question 1b. How many reads are provided and how long are they? Make sure to measure each file separately [Hint: Try `FastQC`]  


\pagebreak

- Question 1c. How much coverage do you expect to have? [Hint: A little arthmetic]

\pagebreak

- Question 1d. Plot the average quality value across the length of the reads [Hint: Screenshot from `FastQC`]